version: 1

disable_existing_loggers: true

formatters:
  default_fmter:
    format: '%(asctime)-8s - %(filename)s - %(funcName)s - %(lineno)d - %(levelname)s - %(message)s'

handlers:
  stdout_handler:
    class: logging.StreamHandler
    level: INFO
    formatter: default_fmter
    stream: ext://sys.stdout

  debug_file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: default_fmter
    filename: logs/日志文件.log
    when: midnight
    backupCount: 10
    encoding: utf8

  info_file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: default_fmter
    filename: logs/战斗日志.log
    when: midnight
    backupCount: 10
    encoding: utf8

loggers:
  asra:
    level: DEBUG
    handlers:
      - stdout_handler
      - debug_file_handler
      - info_file_handler
